### ISSUE TITLE
Compare 2D nnU-Net results with UNet results

### ISSUE THREAD

**Issue by plbenveniste** [ivadomed/model_seg_mouse-sc_wm-gm_t1#36]
- [x] Run Julien's model on nnU-Net formatted test folder. 
- [x] Create gif for visual comparison of nnU-net and U-Net on one full subject (with zero annotation)
- [x] Perform visual analysis/comparison of results with @jcohenadad 
- [x] (if useful)Look into metrics such as Dice to look at similarity/differences between nnU-Net and U-Net results

Related to #30

**Comment by plbenveniste** [comment]
@jcohenadad 
In the [README.md](https://github.com/ivadomed/model_seg_mouse-sc_wm-gm_t1/blob/main/README.md) file, I would replace this:
~~~
PATH_DATA_ZURICH_MOUSE=/path/to/zurich-mouse
~~~
by this instead:
~~~
export PATH_DATA_ZURICH_MOUSE="/path/to/zurich-mouse"
~~~

**Comment by plbenveniste** [comment]
Comparison on one slice from `sub-mouse1_chunk-2_T1w.nii.gz`:
![ezgif com-gif-to-apng (1)](https://github.com/ivadomed/model_seg_mouse-sc_wm-gm_t1/assets/67429280/bc8b018f-b645-4369-beb5-12c7bcd4053b)

Left frame uses code from plb/nnunet branch (utilizes nnU-Netv2). Right frame uses code from main branch (utilizes UNet).

**Comment by plbenveniste** [comment]
Comparison on a few slices of the same subject : `sub-mouse1_chunk-2_T1w.nii.gz`:

https://github.com/ivadomed/model_seg_mouse-sc_wm-gm_t1/assets/67429280/526809e4-6477-4663-983e-0b1498f587f7

**Comment by jcohenadad** [comment]
Suggestion on https://github.com/ivadomed/model_seg_mouse-sc_wm-gm_t1/issues/36#issuecomment-1594843234:
- use the same output values for easier comparison (currently the labels 1/2 are swapped)
- increase much more the gamma/contrast/brightness/exposure on the underlying image-- we cannot see properly

**Comment by plbenveniste** [comment]
UPDATE:
Comparison on one slice from `sub-mouse1_chunk-2_T1w.nii.gz`:

![ezgif com-gif-maker](https://github.com/ivadomed/model_seg_mouse-sc_wm-gm_t1/assets/67429280/8ab31065-7a7f-4c9d-b10c-4c07a2050c12)

Left frame uses code from plb/nnunet branch (utilizes nnU-Netv2). Right frame uses code from main branch (utilizes UNet).

**Comment by plbenveniste** [comment]
UPDATE: 

Comparison on a few slices of the same subject : sub-mouse1_chunk-2_T1w.nii.gz:

https://github.com/ivadomed/model_seg_mouse-sc_wm-gm_t1/assets/67429280/f7323fdd-3b87-4932-84d0-905047a9ca5e

Analysis:
- Propagation of error from the "line" (default from acquisition machine during acquisition) on the left of the image.  ivadomed is more sensitive to the error than nnU-Net is. 
- Sudden appearance of another zone detected as spinal cord for the ivadomed algorithm
- ivadomed tends to "over "label the image. 
- nnU-Net tends to "under" label the image

**Comment by jcohenadad** [comment]
Very cool investigations @plbenveniste . Based on these preliminary visualisations, it seems to me that the nnUnet is more performant. Let's see 3-4 more cases before concluding/deciding what to do next.

**Comment by plbenveniste** [comment]
A few interesting examples to look at (all of the following examples contain 0 slice used for training)  : 

<img width="1680" alt="image" src="https://github.com/ivadomed/model_seg_mouse-sc_wm-gm_t1/assets/67429280/02f02021-a147-485a-8687-24da1bcfce90">
This is mouse-8_chunk-1 (n°66): both models don't perform really well. The segmentations is not performed on the entirety of the spinal cord. However, nnU-Net still performs best

<img width="1680" alt="image" src="https://github.com/ivadomed/model_seg_mouse-sc_wm-gm_t1/assets/67429280/0860d231-d400-4db4-bb8f-15032101d9ea">
This is mouse-12_chunk-1 (n°12): nnU-Net outperforms ivadomed. ivadomed creates an other instance of spinal cord outside of the correct area. 

<img width="1678" alt="image" src="https://github.com/ivadomed/model_seg_mouse-sc_wm-gm_t1/assets/67429280/4cc47bfb-c456-4aa2-8541-4c105ecb31cc">
This is mouse-136_chunk-3 (n°20): High quality segmentation for both models. nnU-Net slightly outperforms ivadomed.

<img width="1680" alt="image" src="https://github.com/ivadomed/model_seg_mouse-sc_wm-gm_t1/assets/67429280/43dd0f6c-3e65-4c90-ba32-3f4eb86cfea7">
This is mouse-1_chunk-4 (n°4): Failure in both case.

**Comment by plbenveniste** [comment]
Conclusion: 
Overall nnU-Netv2 outperforms ivadomed. However, supervision is still necessary as some supervision are of very poor quality. Visual analysis is sufficient to obtain these conclusions; therefore, there is no need to use a Dice or any other metric to evaluate both methods.

**Comment by jcohenadad** [comment]
what would be cool to try is train a 3D nnUnet based in the inferences from your model, and see if it outperforms the 2D approach
