### ISSUE TITLE
Final nnU-Net model training for zurich-mouse

### ISSUE THREAD

**Issue by plbenveniste** [ivadomed/model_seg_mouse-sc_wm-gm_t1#38]
Here is the followed strategy for the final model training for the zurich-mouse dataset for white and grey matter segmentation. 

- [x] Extract annotated 2D slices from the dataset
- [x] Train a 2D nnU-Net model on the annotated slices
- [x] Predict segmentation on full 3D volumes
- [x] Train a 3D nnU-Net model on these segmentations and run inference on entire dataset
- [x] Select some 3D predictions, improve segmentation (by removing sections which are not annotated) and add to initial training dataset
- [x] Train a 3D nnU-Net on the training dataset (slices and selected 3D nnU-Net predictions)
- [x] Test on entire zurich-mouse dataset. 
- [x] Save model and write documentation on how to use it

Related to #32 #37

**Comment by plbenveniste** [comment]
Data pre-processed ! 
Training dataset : 192 files ( 31 3D volume from 3D nnU-Net prediction and 161 annotated slices). 
Conversion to nnU-Net format : ok 
nnU-Net plan and pre-process : ok 

Next: transfer dataset to remote GPU cluster and start training

**Comment by plbenveniste** [comment]
Model trained on the final training dataset. 
Average Dice over all folds: 0.91  🎉
Inference currently running on the entire dataset. 

To do: 
- [ ] convert back to the BIDS format (and add python script to the github)
- [ ] update github `README.md`
- [ ] upload segmentations in the git-annex : instead of `manual-masks` use `3d_nnUNet_masks`

**Comment by plbenveniste** [comment]
The results were converted back to BIDS format. 
However, observing the results (such as sub_mouse1_chunk-4) showed that some regions remained unlabeled. 
I think, it's because those regions are a bit different and have never been labeled before.

**Comment by jcohenadad** [comment]
> Better labelling overall from the nnUNet.

Agreed! I think we can go ahead and publish a release, after making sure there is a clear procedure for running the inference on a single image (ie: update test.py and update README)

**Comment by plbenveniste** [comment]
Selection of the model : 
We want to store the model and at the same time we don't want to take up too much space on Github and we don't want users to have to download a 2GB file in order to use our model. Therefore, we went through the following reasoning process.
First every fold has 2 model stored: the`checkpoint_final.pth` model and the `checkpoint_best.pth`. However, we see that in every case the model follows a continuously growing dice score. Therefore, the `ckeckpoint_best.pth` is the same as the 
`checkpoint_final.pth`.  However, we decided to use the `checkpoint_best.pth` as it is the one to use in case during training the dice scores diminishes at some point (rule of thumb [here](https://github.com/MIC-DKFZ/nnUNet/issues/110#issuecomment-570148725)). 
Also, since every fold perform relatively similar, which means that our dataset is homogeneous, we only retain one fold which has the highest dice score: fold 4.  

Fold selection : 
- fold 0 : 0.9135
- fold 1 : 0.9083
- fold 2 : 0.9109 
- fold 3 : 0.9132
- fold 4 : 0.9173

We also remove files from the model folder which are not useful for inference (validation images, data description ...), except files `training_log.txt`and `progress.png` which can be interesting for users to see how the model was trained and how the training evolved throughout time.

Furthermore, we also decided to keep the post-processing files in the folder in case the person want to perform post-processing on the results of the inference. 

By doing this, we went from 5.6 GB to 280 MB.

**Comment by jcohenadad** [comment]
> Also, since every fold perform relatively similar, which means that our dataset is homogeneous, we only retain one fold which has the highest dice score: fold 4.

We know there is generally an advantage in doing ensembling in terms of segmentation performance, but of course if inference is too slow, then we should revisit.
