### ISSUE TITLE
Find out where models are typically stored

### ISSUE THREAD

**Issue by plbenveniste** [ivadomed/model_seg_mouse-sc_wm-gm_t1#39]
Eg: check on various nnUnet-based projects, are they hosted on GH? if so on the release artifacts (what is max size), if not where do ppl usually store these models?

Related to #38

**Comment by plbenveniste** [comment]
It seems that the best strategy is to host the model in a google drive or dropbox and add the link to the Github page. 
Another solution could be to store the model in the release: but it's meant to make available versions of the code and the model weights don't rely fit in that category. 

Do we have an ivadomed or neuropoly google drive section specifically designed for hosting pre-trained models ?

**Comment by jcohenadad** [comment]
> It seems that the best strategy is to host the model in a google drive or dropbox and add the link to the Github page.

That could be an option indeed. 

> Another solution could be to store the model in the release: but it's meant to make available versions of the code and the model weights don't rely fit in that category.

I think it is totally appropriate to release models as 'release artifacts', as we did [here](https://github.com/ivadomed/model_seg_mouse-sc_wm-gm_t1/releases/tag/v0.2). However, GH artifacts are size limited (I think it is 100MB but we should double check), so if models are larger, then we should host them somewhere else (eg: gdrive as you mentioned).

**Comment by jcohenadad** [comment]
> Should we prefer a realease rather than a google drive then ?

Yes. Better to have it centralized in the same repos (for permission issues) and Gdrive is not accessible in some countries (eg China)
