### ISSUE TITLE
Create simple test.py inference script

### ISSUE THREAD

**Issue by plbenveniste** [ivadomed/model_seg_mouse-sc_wm-gm_t1#40]
similar to https://github.com/ivadomed/model_seg_mouse-sc_wm-gm_t1/blob/main/test.py, but compatible with nnUnet:
- input NIfTI file
- create nnUnet compatible folder structure
- run nnUnet CLI as system call
- reorganize file
- delete temp files
- done

Related to #38

**Comment by plbenveniste** [comment]
Code based on [run_inference.py](https://github.com/ivadomed/model_seg_sci/blob/nk/nnunet-package/packaging/run_inference.py).

**Comment by jcohenadad** [comment]
> Code based on [run_inference.py](https://github.com/ivadomed/model_seg_sci/blob/nk/nnunet-package/packaging/run_inference.py).

this URL points to a code in a branch, which will likely be deleted once the branch is merged (hence will give a 404 error in the futur), so I suggest to instead point to a code in a 'master' version of git. I _think_ that the code in question is this one: https://github.com/ivadomed/utilities/blob/main/packaging/run_nnunet_inference.py
